### ISSUE TITLE
Auto-detect Discord version

### ISSUE THREAD

**Issue by Manoz** [HiDeoo/Unanimity#6]
Reminder? Is there a way to auto-detect the Discord version instead of `var discordVersion = "0.0.xxx";` in `install.js`?

**Comment by HiDeoo** [comment]
That could indeed be a thing but not sure about a "good thing". 

I still need to manually check Discord main index.js file for modifications to ensure that Unanimity is injected at the right place and right time.

https://github.com/HiDeoo/Unanimity/blob/master/install.js#L85-L89

For the time being, I'll manually update Unanimity at every Discord update to avoid any problems, especially on Windows...
